import type { MessageKey, Translator } from '../../app/i18n/config';
const reasons:Record<string,MessageKey>={
  OBSERVATIONS_REQUIRED:'phase5.OBSERVATIONS_REQUIRED',INSUFFICIENT_HISTORY:'phase5.INSUFFICIENT_HISTORY_REASON',MISSING_PERIODS:'phase5.MISSING_PERIODS_REASON',INCOMPATIBLE_SERIES:'phase5.INCOMPATIBLE_SERIES_REASON',QUALITY_RESTRICTION:'phase5.QUALITY_RESTRICTION_REASON',
  ...Object.fromEntries(['INCOMPATIBLE_UNITS','INCOMPATIBLE_PERIOD_LENGTH','PARTIAL_PERIOD','GEOGRAPHY_UNMAPPED','METHODOLOGY_BOUNDARY','UNSUPPORTED_METRIC','ZERO_BASE_GROWTH_UNAVAILABLE','NO_REPEATED_DEMAND_OBSERVATIONS','NO_AVAILABLE_WORKFORCE_SUPPLY','NO_COMPARABLE_DEMAND_SUPPLY','NO_REGIONAL_DEMAND_HISTORY','NO_SKILL_HISTORY','NO_TRAINING_CAPACITY_RELATIONSHIP','COVERAGE_SINGLE_SNAPSHOT','COVERAGE_PARTIAL_PERIOD','COVERAGE_MISSING_PERIOD','COVERAGE_UNMAPPED_GEOGRAPHY','COVERAGE_CLASSIFICATIONS_UNAVAILABLE'].map(k=>[k,`phase5.${k}` as MessageKey])),
  ...Object.fromEntries(['SOURCE_EVIDENCE_REQUIRED','ELIGIBLE_OBSERVED_SERIES','SOURCE_COVERAGE_EVIDENCE','COVERAGE_SINGLE_DEMAND_SNAPSHOT','COVERAGE_SINGLE_REGIONAL_LABOUR_PERIOD','COVERAGE_SINGLE_INFRASTRUCTURE_SNAPSHOT','COVERAGE_QUARANTINED_PERIOD','COVERAGE_CAPACITY_UNAVAILABLE'].map(k=>[k,`phase5.${k}` as MessageKey])),
};
export function reasonLabel(t:Translator,code:string){return t(reasons[code]??'phase5.unknownReason');}
export function stateLabel(t:Translator,state:string){return t(`phase5.${state}` as MessageKey);}
export function metricLabel(t:Translator,metric:string){return ['LFPR','WPR','UR'].includes(metric)?t(`real.${metric}` as MessageKey):['TRAINED','CERTIFIED','TRAINING_CENTRES'].includes(metric)?t(`supply.${metric}` as MessageKey):metric==='active_vacancies'?t('phase5.vacancyStock'):metric;}
export function unitLabel(t:Translator,unit:string){return unit==='percent'?'%':unit==='persons'?t('forecast.persons'):unit==='centres'?t('forecast.centres'):unit==='vacancies'?t('forecast.vacancies'):unit;}
export function contextLabel(t:Translator,identity:Record<string,string|null>){return Object.entries(identity).filter(([key,v])=>['sex','sector','activity_status','programme','population','age_group'].includes(key)&&v).map(([,v])=>v==='15+'?t('real.age'):['persons','female','male','combined','rural','urban','US','CWS'].includes(v??'')?t(`real.${v}` as MessageKey):v).join(' · ');}
export function requiredLabel(t:Translator,kind:string){const keys:Record<string,MessageKey>={DEMAND_ACCELERATION:'warning.requiredDemand',SUPPLY_ACCELERATION:'warning.requiredSupply',DEMAND_SUPPLY_DIVERGENCE:'warning.requiredGap',REGIONAL_DEMAND_ANOMALY:'warning.requiredRegional',EMERGING_SKILL_SIGNAL:'warning.requiredSkill',DECLINING_SKILL_SIGNAL:'warning.requiredSkill',TRAINING_PRESSURE:'warning.requiredCapacity'};return t(keys[kind]??'warning.requiredGeneral');}
