import type { Evidence, Source } from '../real-intelligence/contracts';
import type { Point, Series } from '../forecast/contracts';
export function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid intelligence contract');return value as Record<string,unknown>;}
export function array(value:unknown):unknown[]{if(!Array.isArray(value))throw Error('Invalid intelligence collection');return value;}
export function text(value:unknown):string{if(typeof value!=='string'||!value)throw Error('Invalid intelligence metadata');return value;}
export function strings(value:unknown):string[]{return array(value).map(text);}
export function number(value:unknown):number{if(typeof value!=='number'||!Number.isFinite(value))throw Error('Invalid intelligence value');return value;}
export function count(value:unknown):number{const n=number(value);if(!Number.isSafeInteger(n)||n<0)throw Error('Invalid intelligence count');return n;}
export function nullableNumber(value:unknown):number|null{return value===null?null:number(value);}
export function choice<T extends string>(value:unknown,choices:readonly T[]):T{if(!choices.includes(value as T))throw Error('Unsupported intelligence state');return value as T;}
export function sources(value:unknown):Source[]{const ids=new Set<string>();array(value).forEach(v=>{const s=object(v);['source_id','publisher','dataset_name','url','methodology','notes'].forEach(k=>text(s[k]));if(ids.has(String(s.source_id))||s.connected!==true||!/^https?:\/\//.test(String(s.url))||s.license_url!==undefined&&s.license_url!==null&&!/^https?:\/\//.test(String(s.license_url))||! /^[a-f0-9]{64}$/.test(text(s.sha256)))throw Error('Unverified source');ids.add(String(s.source_id));});return value as Source[];}
export function evidence(value:unknown,registry:Source[]):Evidence{const e=object(value),source=registry.find(s=>s.source_id===e.source_id);text(e.locator);strings(e.transformations);if(!source||e.raw_sha256!==source.sha256)throw Error('Evidence is not bound to its source');return e as unknown as Evidence;}
export function point(value:unknown,registry:Source[]):Point{const p=object(value);['observation_id','period','period_start','period_end','unit','original_value','original_unit','source_id','source_version','publication_version','quality_status'].forEach(k=>text(p[k]));object(p.identity);const source=registry.find(s=>s.source_id===p.source_id);if(p.status!=='OBSERVED'||number(p.value)<0||p.unit==='percent'&&number(p.value)>100||typeof p.partial!=='boolean'||!/^\d{4}-\d{2}-\d{2}$/.test(String(p.period_start))||!/^\d{4}-\d{2}-\d{2}$/.test(String(p.period_end))||String(p.period_end)<String(p.period_start)||evidence(p.evidence,registry).source_id!==p.source_id||p.source_version!==(source?.version||'unspecified'))throw Error('Invalid observed baseline');return p as unknown as Point;}
export function series(value:unknown,registry:Source[]):Series{const s=object(value);['series_id','metric','unit','geography_name','frequency','methodology_version'].forEach(k=>text(s[k]));choice(s.family,['labour','demand','supply']);const classification=object(s.classification),sourceIds=strings(s.source_ids);strings(s.missing_periods);strings(s.limitations);let last='';const ids=new Set<string>();array(s.observations).forEach(v=>{const p=point(v,registry),expected={...classification,family:s.family,metric:s.metric,geography_id:s.geography_id,frequency:s.frequency,unit:s.unit,methodology_version:s.methodology_version};if(ids.has(p.observation_id)||p.period_start<=last||p.unit!==s.unit||!sourceIds.includes(p.source_id)||Object.entries(expected).some(([k,v])=>p.identity[k]!==v))throw Error('Invalid series identity or chronology');ids.add(p.observation_id);last=p.period_start;});return s as unknown as Series;}
export function sameRecord(a:Record<string,unknown>,b:Record<string,unknown>):boolean{return Object.keys(a).length===Object.keys(b).length&&Object.entries(a).every(([k,v])=>v===b[k]);}
export function sameEvidence(a:Evidence,b:Evidence):boolean{return a.source_id===b.source_id&&a.locator===b.locator&&a.raw_sha256===b.raw_sha256&&a.transformations.length===b.transformations.length&&a.transformations.every((v,i)=>v===b.transformations[i]);}
function date(value:string){const d=new Date(`${value}T00:00:00Z`);if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==value)throw Error('Invalid observation date');return d;}
function yearLater(value:string){const d=date(value),month=d.getUTCMonth();d.setUTCFullYear(d.getUTCFullYear()+1);if(d.getUTCMonth()!==month)d.setUTCDate(0);return d;}
export function annual(p:Point){const end=yearLater(p.period_start);end.setUTCDate(end.getUTCDate()-1);return end.toISOString().slice(0,10)===p.period_end;}
export function adjacent(a:Point,b:Point){const start=date(a.period_end);start.setUTCDate(start.getUTCDate()+1);return start.toISOString().slice(0,10)===b.period_start&&yearLater(a.period_end).toISOString().slice(0,10)===b.period_end;}
export function equal(a:unknown,b:number){if(!Number.isFinite(b)||Math.abs(number(a)-b)>1e-7*Math.max(1,Math.abs(b)))throw Error('Unsubstantiated derived value');}
