import type {Evidence,Source} from '../real-intelligence/contracts';
import type {Point,Series,Family} from '../forecast/contracts';
import {annual,array,choice,count,equal,evidence,number,object,point,sameRecord,series,sources,strings,text} from '../phase5/validation';
export type ScenarioType='SKILL_SHOCK'|'DIRECT_METRIC_SENSITIVITY';
export type AssumptionKind='AI_ADOPTION'|'AUTOMATION'|'SECTOR_EXPANSION'|'DIRECT_METRIC_CHANGE';
export interface Assumption{kind:AssumptionKind;change_percent:number}
export interface ScenarioRequest{scenario_type:ScenarioType;series_id:string;assumption:Assumption}
export interface BaselineOption{series_id:string;family:Family;metric:string;unit:string;geography_id:string;geography_name:string;period:string;value:number;classification:Record<string,string|null>;baseline_observation_id:string}
export interface ScenarioCoverage{version:string;status:'AVAILABLE'|'EMPTY'|'UNAVAILABLE';scenario_types:{scenario_type:ScenarioType;status:'READY'|'NOT_READY';reason_codes:string[];required_data:string[]}[];geographies:{id:string;name:string}[];baseline_total:number;limit:number;offset:number;baseline_options:BaselineOption[];relationships_status:'UNAVAILABLE';sources:Source[];limitations:string[]}
export interface ScenarioResult{version:string;scenario_id:string;scenario_type:ScenarioType;status:'SCENARIO'|'NOT_READY'|'UNAVAILABLE';is_simulation:true;disclosure:'SIMULATION — NOT OBSERVED DATA';assumptions:Assumption[];baseline:Point|null;series:Series|null;results:{status:'SCENARIO';simulation:true;baseline_observation_id:string;baseline_value:number;value:number;absolute_change:number;change_percent:number;unit:string;period:string;geography_id:string;rule_id:'direct-metric-sensitivity-1.0'}[];affected_entities:{entity_type:'metric';entity_id:string;label:string}[];impact_rules:{rule_id:string;rule_kind:'DIRECT_ASSUMPTION';expression_id:'BASELINE_PERCENT_MULTIPLIER';coefficient_origin:'USER_ASSUMPTION'}[];relationships:unknown[];reason_codes:string[];required_data:string[];evidence:Evidence[];sources:Source[];methodology_version:'scenario-gate-1.0';methodology:string;limitations:string[];uncertainty:{status:'UNAVAILABLE';reason:string}}
export function validateAssumption(v:unknown):Assumption{const a=object(v);choice(a.kind,['AI_ADOPTION','AUTOMATION','SECTOR_EXPANSION','DIRECT_METRIC_CHANGE']);const n=number(a.change_percent);if(n< -100||n>1000)throw Error('Unsupported assumption range');return a as unknown as Assumption;}
export function decodeScenarioCoverage(v:unknown):ScenarioCoverage{const c=object(v);text(c.version);choice(c.status,['AVAILABLE','EMPTY','UNAVAILABLE']);sources(c.sources);const total=count(c.baseline_total);count(c.limit);count(c.offset);if(c.relationships_status!=='UNAVAILABLE')throw Error('Unsupported relationship claim');strings(c.limitations);array(c.geographies).forEach(v=>{const g=object(v);text(g.id);text(g.name);});array(c.scenario_types).forEach(v=>{const s=object(v);choice(s.scenario_type,['SKILL_SHOCK','DIRECT_METRIC_SENSITIVITY']);choice(s.status,['READY','NOT_READY']);strings(s.reason_codes);strings(s.required_data);if(s.scenario_type==='SKILL_SHOCK'&&s.status==='READY'||s.scenario_type==='DIRECT_METRIC_SENSITIVITY'&&(s.status==='READY')!==(total>0))throw Error('Unsupported scenario readiness');});
  array(c.baseline_options).forEach(v=>{const b=object(v);['series_id','metric','unit','geography_id','geography_name','period','baseline_observation_id'].forEach(k=>text(b[k]));choice(b.family,['labour','demand','supply']);object(b.classification);if(number(b.value)<0||b.unit==='percent'&&number(b.value)>100)throw Error('Invalid baseline option');});if(array(c.baseline_options).length>total||c.status!=='AVAILABLE'&&total>0)throw Error('Invalid baseline coverage');return c as unknown as ScenarioCoverage;}
export function decodeScenario(v:unknown):ScenarioResult{const r=object(v);text(r.version);text(r.scenario_id);choice(r.scenario_type,['SKILL_SHOCK','DIRECT_METRIC_SENSITIVITY']);choice(r.status,['SCENARIO','NOT_READY','UNAVAILABLE']);const registry=sources(r.sources);if(r.is_simulation!==true||r.disclosure!=='SIMULATION — NOT OBSERVED DATA'||r.methodology_version!=='scenario-gate-1.0')throw Error('Missing simulation disclosure');text(r.methodology);strings(r.limitations);strings(r.reason_codes);strings(r.required_data);const uncertainty=object(r.uncertainty);if(uncertainty.status!=='UNAVAILABLE')throw Error('Unsupported uncertainty');text(uncertainty.reason);const assumptions=array(r.assumptions).map(validateAssumption);if(assumptions.length!==1||(r.scenario_type==='DIRECT_METRIC_SENSITIVITY')!==(assumptions[0].kind==='DIRECT_METRIC_CHANGE'))throw Error('Invalid scenario assumptions');const baseline=r.baseline===null?null:point(r.baseline,registry),s=r.series===null?null:series(r.series,registry),ev=array(r.evidence).map(v=>evidence(v,registry));
  if(array(r.relationships).length)throw Error('Unverified scenario relationship');
  if(baseline&&(!s||baseline.partial||baseline.quality_status!=='VALID'||baseline.as_of!==null&&baseline.period_end>baseline.as_of||s.geography_id===null||!s.observations.some(p=>p.observation_id===baseline.observation_id&&p.value===baseline.value&&p.unit===baseline.unit&&p.source_id===baseline.source_id&&p.source_version===baseline.source_version&&p.publication_version===baseline.publication_version&&p.period_start===baseline.period_start&&p.period_end===baseline.period_end&&p.period===baseline.period&&p.original_value===baseline.original_value&&p.original_unit===baseline.original_unit&&sameRecord(p.identity,baseline.identity)&&JSON.stringify(p.evidence)===JSON.stringify(baseline.evidence))||!ev.some(e=>JSON.stringify(e)===JSON.stringify(baseline.evidence))))throw Error('Unsupported observed baseline');
  if(r.status!=='SCENARIO'){if(array(r.results).length||array(r.impact_rules).length||array(r.affected_entities).length||!array(r.reason_codes).length)throw Error('Unavailable scenario contains invented outputs');}
  else {if(r.scenario_type!=='DIRECT_METRIC_SENSITIVITY'||!baseline||!s||array(r.results).length!==1||array(r.impact_rules).length!==1||array(r.affected_entities).length!==1||array(r.reason_codes).length||array(r.required_data).length)throw Error('Ungated scenario');const last=s.observations.filter(p=>!p.partial&&p.quality_status==='VALID'&&p.unit===s.unit&&(p.as_of===null||p.period_end<=p.as_of)&&(s.frequency==='POINT'||annual(p))&&(!s.applicability_end||p.period_end<=s.applicability_end)).at(-1);if(last?.observation_id!==baseline.observation_id)throw Error('Baseline is not the last eligible complete observation');
    const result=object(array(r.results)[0]),rule=object(array(r.impact_rules)[0]),entity=object(array(r.affected_entities)[0]);if(result.status!=='SCENARIO'||result.simulation!==true||result.baseline_observation_id!==baseline.observation_id||result.baseline_value!==baseline.value||result.change_percent!==assumptions[0].change_percent||result.unit!==baseline.unit||result.period!==baseline.period||result.geography_id!==s.geography_id||result.rule_id!=='direct-metric-sensitivity-1.0'||rule.rule_id!==result.rule_id||rule.rule_kind!=='DIRECT_ASSUMPTION'||rule.expression_id!=='BASELINE_PERCENT_MULTIPLIER'||rule.coefficient_origin!=='USER_ASSUMPTION'||entity.entity_type!=='metric'||entity.entity_id!==s.series_id||entity.label!==s.metric)throw Error('Unsupported scenario rule');const simulated=baseline.value*(1+assumptions[0].change_percent/100);equal(result.value,simulated);equal(result.absolute_change,simulated-baseline.value);if(simulated<0||baseline.unit==='percent'&&simulated>100)throw Error('Out-of-domain simulation');
  }
  return r as unknown as ScenarioResult;
}
