import {useLocale} from '../../hooks/usePreferences';
import type {MessageKey} from '../../app/i18n/config';
import {StatusBadge} from '../../components/ui/StatusBadge';
import {contextLabel,metricLabel,unitLabel} from '../phase5/labels';
import type {EvidenceSelection} from '../early-warning/WarningDetail';
import type {ScenarioResult as Result} from './contracts';
export function ScenarioResult({result,onEvidence}:{result:Result;onEvidence:(value:EvidenceSelection)=>void}){const {t,locale}=useLocale(),nf=new Intl.NumberFormat(locale,{maximumFractionDigits:3}),df=new Intl.NumberFormat(locale,{maximumFractionDigits:3,signDisplay:'exceptZero'}),b=result.baseline,s=result.series,r=result.results[0];return <section className="scenario-result phase5-detail" aria-labelledby="scenario-result-heading" data-status={result.status}>
  <header><p className="section-kicker scenario-disclosure">{t('scenario.simulation')}</p><h2 id="scenario-result-heading">{t(result.status==='SCENARIO'?'scenario.result':'scenario.notReady')}</h2><StatusBadge kind={result.status==='SCENARIO'?'scenario':'unavailable'}/></header>
  {result.status==='SCENARIO'&&r?<><dl className="phase5-facts scenario-values"><div><dt>{t('scenario.baseline')} · {t('real.observed')}</dt><dd>{nf.format(r.baseline_value)} <small>{unitLabel(t,r.unit)}</small></dd></div><div><dt>{t('scenario.impact')} · {t('common.scenario')}</dt><dd>{nf.format(r.value)} <small>{unitLabel(t,r.unit)}</small></dd></div><div><dt>{t('scenario.delta')}</dt><dd>{df.format(r.absolute_change)} <small>{r.unit==='percent'?t('phase5.pp'):unitLabel(t,r.unit)}</small></dd></div></dl><p className="scenario-formula">{t('scenario.formula')}</p><p>{t('scenario.directNote')}</p>{r.unit!=='percent'&&<p>{t('scenario.countNote')}</p>}</>:<section className="phase5-gate"><h3>{t('phase5.noNumber')}</h3><ul>{result.reason_codes.map(code=><li key={code}>{t(`scenario.${code}` as MessageKey)}</li>)}</ul><h3>{t('scenario.required')}</h3><ul>{result.required_data.map(code=><li key={code}>{t(`scenario.${code}` as MessageKey)}</li>)}</ul></section>}
  {b&&s&&<section className="scenario-baseline-evidence"><h3>{t('scenario.baseline')}</h3><p>{metricLabel(t,s.metric)} · <span lang="en">{s.geography_name}</span> · {b.period}</p><p>{contextLabel(t,s.classification)}</p><p><strong>{nf.format(b.value)} {unitLabel(t,b.unit)}</strong> · <StatusBadge kind="observed"/></p><button type="button" className="real-evidence-link" aria-label={`${t('phase5.evidence')} ${b.period}`} onClick={()=>onEvidence({evidence:b.evidence,source:result.sources.find(x=>x.source_id===b.source_id),period:`${b.period} · ${s.geography_name}`})}>{t('phase5.evidence')}</button><p>{t('scenario.baselineNote')}</p></section>}
  <section><h3>{t('scenario.assumptions')}</h3><dl className="phase5-facts"><div><dt>{t('scenario.mode')}</dt><dd>{t(`scenario.${result.scenario_type}`)}</dd></div>{result.assumptions.map(a=><div key={a.kind}><dt>{t(`scenario.${a.kind}`)}</dt><dd>{df.format(a.change_percent)}%</dd></div>)}</dl></section>
  <details className="phase5-method"><summary>{t('scenario.methodology')}</summary><p>{t(result.scenario_type==='SKILL_SHOCK'?'scenario.shockNote':'scenario.directNote')}</p><p lang="en">{result.methodology}</p><code lang="en">{result.methodology_version}</code>{result.impact_rules.map(rule=><p lang="en" key={rule.rule_id}>{rule.rule_id} · {rule.expression_id} · {rule.coefficient_origin}</p>)}</details>
  <section><h3>{t('phase5.limitations')} / {t('scenario.uncertainty')}</h3><p>{t('scenario.relationshipNote')}</p><p>{t('scenario.uncertaintyNote')}</p><p>{t('scenario.limitNote')}</p><details className="phase5-method"><summary>{t('phase5.technical')}</summary><p lang="en">{result.uncertainty.reason}</p><ul lang="en">{result.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul><p>{t('phase5.sourceNative')}</p></details></section>
  </section>;}
