import { useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, Scale, Check, Minus } from 'lucide-react';
import { useLocale } from '../../hooks/usePreferences';
import { ErrorState, LoadingState, EmptyState } from '../../components/ui/States';
import { SecondaryButton } from '../../components/ui/Buttons';
import { EvidencePanel } from '../real-intelligence/EvidencePanel';
import type { SelectedEvidence } from '../supply/TaxonomyDesk';
import type { MessageKey } from '../../app/i18n/config';
import type { GapAssessment, GapMeasure } from './contracts';
import { useGaps } from './useGaps';

const filterKeys = ['dimension','geography_id','geography_level','reference_period','skill_code','occupation_code','sector_code','readiness','quality_status','gap_direction','offset'];
export function GapIntelligence() {
  const {t,locale} = useLocale(), [params,setParams] = useSearchParams();
  const [evidence,setEvidence] = useState<SelectedEvidence|null>(null), [pairId,setPairId] = useState('');
  const details = useRef<HTMLDetailsElement>(null);
  const filters = new URLSearchParams([...params].filter(([k,v]) => filterKeys.includes(k) && v));
  if(!params.has('geography_id')) filters.set('geography_id','in');
  if(!params.has('dimension')) filters.set('dimension','skill');
  const query = filters.toString(), {data,coverage,failed,retry} = useGaps(query), nf = new Intl.NumberFormat(locale,{maximumFractionDigits:2});
  const label = (key:string) => t(`gap.${key}` as MessageKey);
  function change(key:string,value:string) { const next = new URLSearchParams(params); next.set(key,value); if(key!=='offset') next.delete('offset'); setParams(next); }
  if(failed) return <ErrorState description={t('gap.error')} onRetry={retry}/>;
  if(!data || !coverage) return <LoadingState label={t('gap.loading')}/>;
  const pair: GapAssessment | undefined = data.items.length ? data.items.find(r => r.result_id === pairId) ?? data.items[0] : undefined;
  const state = pair?.readiness ?? data.status;
  function sourceEvidence(row:GapMeasure) { const source = data!.sources.find(s => s.source_id === row.source_id); if(source) setEvidence({evidence:row.evidence,source,period:`${row.reference_period} · ${row.source_geography_label}`}); }
  function openAssessment() { if(details.current) { details.current.open=true; details.current.querySelector('summary')?.focus(); details.current.scrollIntoView({block:'start',behavior:'instant'}); } }
  function metric(row:GapMeasure) { return row.metric === 'active_vacancies' ? t('demand.active') : ['TRAINED','CERTIFIED','TRAINING_CENTRES'].includes(row.metric) ? t(`supply.${row.metric}` as MessageKey) : row.metric; }
  function observation(row:GapMeasure,side:'demand'|'supply') { return <article className="gap-source-observation"><p className="gap-eyebrow">{label(side)}</p><h3>{metric(row)}</h3><strong>{nf.format(row.value)}</strong><p>{row.unit === 'persons' ? t('supply.persons') : row.unit === 'centres' ? t('supply.centres') : row.unit === 'vacancies' ? t('demand.vacancies') : row.unit}</p><p><span lang="en">{row.source_geography_label}</span> · {row.reference_period}</p><p className="real-note"><span lang="en">{data!.sources.find(s => s.source_id === row.source_id)?.publisher}</span> · {t('real.observed')}</p><button type="button" className="real-evidence-link" onClick={() => sourceEvidence(row)} aria-label={`${t('real.evidence')} · ${label(side)}`}>{t('real.evidence')}<ArrowRight size={14} aria-hidden="true"/></button></article>; }
  function result(a:GapAssessment) { if(a.readiness !== 'READY' || !a.demand || !a.supply || a.gap_value === null) return null; return <section className="gap-calculation" aria-label={t('gap.value')}><p className="gap-eyebrow">{t('gap.derived')}</p><dl>{[['gap.demand',nf.format(a.demand.value)],['gap.supply',nf.format(a.supply.value)],['gap.value',nf.format(a.gap_value)],['gap.coverage',a.coverage_ratio === null ? t('gap.undefinedRatio') : new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:2}).format(a.coverage_ratio)]].map(([key,value]) => <div key={key}><dt>{t(key as MessageKey)}</dt><dd>{value}</dd></div>)}</dl><p>{label(a.gap_direction!)} · {a.demand.unit}</p><p className="real-note">{t('gap.formula')}</p><p className="real-note">{t('gap.causalNote')}</p></section>; }
  return <div className="gap-intelligence" data-query={query} data-gap-state={state}>
    <header className="gap-heading"><p className="gap-eyebrow">{t('gap.kicker')}</p><h2>{t('gap.title')}</h2><p>{t('gap.intro')}</p></header>
    <div className="real-filter-bar gap-filters">
      <label>{t('gap.dimension')}<select aria-label={t('gap.dimension')} value={filters.get('dimension')!} onChange={e => change('dimension',e.target.value)}>{['skill','occupation','industry','geography'].map(d => <option value={d} key={d}>{label(d)}</option>)}</select></label>
      <label>{t('real.region')}<select aria-label={t('real.region')} value={filters.get('geography_id') ?? ''} onChange={e => change('geography_id',e.target.value)}><option value="">{t('gap.allRegions')}</option>{coverage.options.geographies.map(g => <option value={g.geography_id} key={g.geography_id}>{g.name}</option>)}{filters.get('geography_id') && !coverage.options.geographies.some(g=>g.geography_id===filters.get('geography_id')) && <option value={filters.get('geography_id')!}>{t('real.unavailable')}</option>}</select></label>
      <label>{t('gap.commonPeriod')}<select aria-label={t('gap.commonPeriod')} disabled={!coverage.options.reference_period.length} value={params.get('reference_period') ?? ''} onChange={e => change('reference_period',e.target.value)}><option value="">{coverage.options.reference_period.length ? t('supply.allPeriods') : t('gap.noPeriod')}</option>{coverage.options.reference_period.map(p=><option key={p}>{p}</option>)}</select></label>
      <label>{t('gap.readiness')}<select aria-label={t('gap.readiness')} value={params.get('readiness') ?? ''} onChange={e => change('readiness',e.target.value)}><option value="">{t('gap.allReadiness')}</option>{coverage.options.readiness.map(r=><option value={r} key={r}>{label(r)}</option>)}</select></label>
      <label>{t('gap.quality')}<select aria-label={t('gap.quality')} value={params.get('quality_status') ?? ''} onChange={e=>change('quality_status',e.target.value)}><option value="">{t('gap.allQuality')}</option>{coverage.options.quality_status.map(q=><option key={q} value={q}>{label(q)}</option>)}</select></label>
      <SecondaryButton onClick={()=>setParams({})}>{t('supply.reset')}</SecondaryButton>
    </div><p className="real-note">{t('gap.filtersNote')}</p>
    <details className="gap-mapping-filters"><summary>{t('gap.skill')} / {t('gap.occupation')} / {t('gap.industry')} / {t('gap.direction')}</summary><div className="real-filter-bar">{(['skill_code','occupation_code','sector_code','gap_direction'] as const).map((key,i)=><label key={key}>{label(['skill','occupation','industry','direction'][i])}<select disabled={!coverage.options[key].length} value={params.get(key)??''} onChange={e=>change(key,e.target.value)} aria-label={label(['skill','occupation','industry','direction'][i])}><option value="">{t(key==='gap_direction'?'gap.noDirection':'gap.noMapping')}</option>{coverage.options[key].map(code=><option value={code} key={code}>{key==='gap_direction'?label(code):code}</option>)}</select></label>)}</div></details>
    {!pair ? <EmptyState title={label(state)} description={t(state==='EMPTY'?'gap.emptyNote':'gap.unavailableNote')}/> : <>
      {data.status==='PARTIAL' && pair.readiness==='READY' && <p className="real-note">{t('gap.partialNote')}</p>}
      {pair.readiness==='READY' ? result(pair) : <section className="gap-gate"><Scale size={26} aria-hidden="true"/><div><p className="gap-eyebrow">{label(pair.readiness)}</p><h3>{t('gap.UNAVAILABLE')}</h3><p>{t(pair.readiness==='PARTIAL'?'gap.partialNote':'gap.blocked')}</p><SecondaryButton onClick={openAssessment}>{t('gap.assessment')}<ArrowRight size={15} aria-hidden="true"/></SecondaryButton></div></section>}
      <section className="gap-context"><h3>{t(pair.readiness==='READY'?'gap.comparableSources':'gap.context')}</h3><p>{t(pair.readiness==='READY'?'gap.comparableContext':'gap.contextNote')}</p><label className="gap-pair-select">{t('gap.choosePair')}<select aria-label={t('gap.choosePair')} value={pair.result_id} onChange={e=>setPairId(e.target.value)}>{data.items.map(a=><option value={a.result_id} key={a.result_id}>{a.demand?.source_geography_label} · {a.demand?.reference_period} ↔ {a.supply?.reference_period} · {a.supply ? metric(a.supply) : t('real.unavailable')}</option>)}</select></label><p className="real-note">{t('gap.pairCount',{count:nf.format(data.total),calculated:nf.format(data.calculated_total)})}</p><div className="gap-source-grid">{pair.demand && observation(pair.demand,'demand')}{pair.supply && observation(pair.supply,'supply')}</div></section>
      {(data.total > 50 || params.has('offset')) && <div className="gap-pagination"><SecondaryButton disabled={!Number(params.get('offset')??0)} onClick={()=>change('offset',String(Math.max(0,Number(params.get('offset')??0)-50)))}>{t('gap.previous')}</SecondaryButton><SecondaryButton disabled={Number(params.get('offset')??0)+data.items.length>=data.total} onClick={()=>change('offset',String(Number(params.get('offset')??0)+50))}>{t('gap.next')}</SecondaryButton></div>}
      <details ref={details} className="gap-assessment"><summary>{t('gap.compatibility')}<span>{label(pair.readiness)}</span></summary><p>{t('gap.compatibilityNote')}</p><ul className="gap-checks">{pair.checks.map(c=><li key={c.dimension}><div><span className="gap-check-icon" aria-hidden="true">{c.status==='COMPATIBLE'?<Check size={16}/>:<Minus size={16}/>}</span><strong>{label(`check.${c.dimension}`)}</strong><span className="gap-check-status">{label(c.status)}</span></div><p>{label(`reason.${c.dimension}`)}</p><code lang="en">{c.reason_code}</code></li>)}</ul></details>
      <section className="gap-evidence"><h3>{t('gap.evidence')}</h3>{pair.evidence.map((ev,i)=>{const source=data.sources.find(s=>s.source_id===ev.source_id);return source && <button type="button" className="real-evidence-link" key={`${ev.source_id}-${i}`} onClick={()=>setEvidence({evidence:ev,source,period:`${pair.demand?.reference_period} ↔ ${pair.supply?.reference_period}`})}><span lang="en">{source.dataset_name}</span><ArrowRight size={14} aria-hidden="true"/></button>;})}{pair.readiness==='READY' && <><h4>{t('gap.method')}</h4><p lang="en">{pair.method_id} · {pair.method_version} · {pair.methodology}</p><details><summary>{t('gap.transforms')}</summary><ul lang="en">{pair.transformations.map((step,i)=><li key={i}>{step}</li>)}</ul></details><h4>{t('gap.limits')}</h4><ul lang="en">{pair.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></>}</section>
    </>}
    <section className="gap-capabilities"><h3>{t('gap.coverageTitle')}</h3><dl>{coverage.items.map(c=><div key={c.dimension}><dt>{label(c.dimension)}</dt><dd>{t(c.gap_status==='DERIVED'?'gap.READY':'gap.UNAVAILABLE')}</dd></div>)}</dl></section>
    <section className="gap-unlock"><h3>{t('gap.unlock')}</h3><p>{t('gap.unlockNote')}</p><p className="real-note">{t('gap.quarantine')}</p><div><Link to="/demand">{t('gap.demandLink')}<ArrowRight size={15} aria-hidden="true"/></Link><Link to="/supply">{t('gap.supplyLink')}<ArrowRight size={15} aria-hidden="true"/></Link></div></section>
    {evidence && <EvidencePanel {...evidence} onClose={()=>setEvidence(null)}/>}
  </div>;
}
