import { useState, type FormEvent } from 'react';
import { useLocale } from '../../hooks/usePreferences';
import { useAuth } from '../../app/providers/authContext';
import { useIntelligenceData } from '../real-intelligence/dataContext';
import type { ProfileSections, UserSkill } from './contracts';
import { accountRequest, AccountError } from './api';
import { Button } from '../../components/ui/Buttons';
import type { MessageKey } from '../../app/i18n/config';

import { type EditableSection, latestCompletionYear } from './config';
const qualifications=['below_matric','matric','secondary','diploma','undergraduate','graduate','postgraduate','doctorate','other','prefer_not'] as const;
const interests=['technology','ai','cybersecurity','data','finance','healthcare','manufacturing','agriculture','construction','education','government','design','business'] as const;
const goals=['job','switch','upskill','choose','training','business','labour','government','explore'] as const;

export function ProfileEditor({section,initial,onSaved,onboarding=false}:{section:EditableSection|'experience';initial:ProfileSections;onSaved:()=>Promise<void>;onboarding?:boolean}) {
  const {t}=useLocale();const {csrf}=useAuth();const {catalog}=useIntelligenceData();
  const [draft,setDraft]=useState(initial);const [search,setSearch]=useState('');const [skillName,setSkillName]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState<MessageKey|null>(null);
  const toggle=(values:string[],value:string)=>values.includes(value)?values.filter(v=>v!==value):[...values,value];
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage(null);try{await accountRequest('/v1/me/sections/'+section,csrf,'PUT',draft[section]);await onSaved();setMessage('personal.saved');}catch(e){setMessage(e instanceof AccountError?e.key:'personal.error');}finally{setBusy(false);}}
  function addSkill(){const clean=skillName.trim();if(!clean || draft.skills.some(s=>s.name.toLocaleLowerCase()===clean.toLocaleLowerCase()))return;const skill:UserSkill={name:clean,canonical_id:null,taxonomy:null,proficiency:'',origin:'SELF_REPORTED',resume_id:null};setDraft({...draft,skills:[...draft.skills,skill]});setSkillName('');}
  return <form className="personal-editor" onSubmit={save}>
    {!onboarding && <h2>{t(`personal.${section}`)}</h2>}
    {section==='education' && <><label>{t('personal.qualification')}<select aria-label={t("personal.qualification")} value={draft.education.qualification} onChange={e=>setDraft({...draft,education:{...draft.education,qualification:e.target.value,origin:'SELF_REPORTED',resume_id:null}})}><option value="">{t('personal.unspecified')}</option>{qualifications.map(id=><option key={id} value={id}>{t(`personal.q.${id}`)}</option>)}</select></label>
      {(['degree','field'] as const).map(key=><label key={key}>{t(`personal.${key}`)}<input maxLength={120} value={draft.education[key]} onChange={e=>setDraft({...draft,education:{...draft.education,[key]:e.target.value,origin:'SELF_REPORTED',resume_id:null}})}/></label>)}
      <label>{t('personal.year')}<input type="number" min={1900} max={latestCompletionYear} value={draft.education.year??''} onChange={e=>setDraft({...draft,education:{...draft.education,year:e.target.value?Number(e.target.value):null,origin:'SELF_REPORTED',resume_id:null}})}/></label><p className="personal-note">{t(draft.education.origin==='RESUME_DERIVED'?'personal.resumeOrigin':'personal.origin')}</p></>}
    {section==='interests' && <><label>{t('personal.search')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><fieldset className="choice-list"><legend className="sr-only">{t('personal.interests')}</legend>{interests.filter(id=>t(`personal.i.${id}`).toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(id=><label key={id}><input type="checkbox" checked={draft.interests.includes(id)} onChange={()=>setDraft({...draft,interests:toggle(draft.interests,id)})}/>{t(`personal.i.${id}`)}</label>)}</fieldset></>}
    {section==='skills' && <><p className="personal-note">{t('personal.noTaxonomy')}</p><div className="personal-inline"><label>{t('personal.addSkill')}<input maxLength={100} value={skillName} onChange={e=>setSkillName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill();}}}/></label><Button variant="secondary" disabled={!skillName.trim() || draft.skills.length>=50} onClick={addSkill}>{t('personal.add')}</Button></div>
      <label>{t('personal.search')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><ul className="user-skills">{draft.skills.map((skill,index)=>skill.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())?<li key={skill.name+index}><div><strong>{skill.name}</strong><small>{t(skill.origin==='RESUME_DERIVED'?'personal.resumeOrigin':'personal.origin')}</small></div><label><span className="sr-only">{t('personal.proficiency')} · {skill.name}</span><select aria-label={t("personal.proficiency")+" · "+skill.name} value={skill.proficiency} onChange={e=>setDraft({...draft,skills:draft.skills.map((s,i)=>i===index?{...s,proficiency:e.target.value as UserSkill['proficiency'],origin:'SELF_REPORTED',resume_id:null}:s)})}><option value="">{t('personal.unspecified')}</option>{(['beginner','intermediate','advanced'] as const).map(id=><option key={id} value={id}>{t(`personal.${id}`)}</option>)}</select></label><Button variant="quiet" aria-label={t('personal.remove',{name:skill.name})} onClick={()=>setDraft({...draft,skills:draft.skills.filter((_,i)=>i!==index)})}>×</Button></li>:null)}</ul></>}
    {section==='experience' && <ul className="user-skills">{draft.experience.map((item,index)=><li key={index}><label><span>{t('personal.experience')} · {index+1}</span><input maxLength={120} value={item.name} onChange={e=>setDraft({...draft,experience:draft.experience.map((v,i)=>i===index?{...v,name:e.target.value,origin:'SELF_REPORTED',resume_id:null}:v)})}/><small>{t(item.origin==='RESUME_DERIVED'?'personal.resumeOrigin':'personal.origin')}</small></label><Button variant="quiet" aria-label={t('personal.remove',{name:item.name})} onClick={()=>setDraft({...draft,experience:draft.experience.filter((_,i)=>i!==index)})}>×</Button></li>)}</ul>}
    {section==='career' && <><fieldset className="choice-list"><legend className="sr-only">{t('personal.career')}</legend>{goals.map(id=><label key={id}><input type="checkbox" checked={draft.career.goals.includes(id)} onChange={()=>setDraft({...draft,career:{...draft.career,goals:toggle(draft.career.goals,id)}})}/>{t(`personal.g.${id}`)}</label>)}</fieldset><label>{t('personal.goalNote')}<textarea maxLength={500} value={draft.career.note} onChange={e=>setDraft({...draft,career:{...draft.career,note:e.target.value}})}/></label></>}
    {section==='geography' && <><p className="personal-note">{t('personal.geoNote')}</p><label>{t('personal.currentRegion')}<select aria-label={t("personal.currentRegion")} value={draft.geography.current||''} onChange={e=>setDraft({...draft,geography:{...draft.geography,current:e.target.value||null}})}><option value="">{t('personal.unspecified')}</option>{catalog?.regions.map(r=><option key={r.region_id} value={r.region_id}>{r.name}</option>)}</select></label><label>{t('personal.search')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><fieldset className="choice-list bounded-choices"><legend>{t('personal.preferred')}</legend>{catalog?.regions.filter(r=>r.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(r=><label key={r.region_id}><input type="checkbox" checked={draft.geography.preferred.includes(r.region_id)} onChange={()=>setDraft({...draft,geography:{...draft.geography,preferred:toggle(draft.geography.preferred,r.region_id)}})}/>{r.name}</label>)}</fieldset>{(['relocation','remote'] as const).map(key=><label className="personal-check" key={key}><input type="checkbox" checked={draft.geography[key]} onChange={e=>setDraft({...draft,geography:{...draft.geography,[key]:e.target.checked}})}/>{t(`personal.${key}`)}</label>)}</>}
    <div className="personal-actions"><Button type="submit" pending={busy}>{t(onboarding?'personal.continue':'personal.save')}</Button>{message && <p role={message==='personal.saved'?'status':'alert'}>{t(message)}</p>}</div>
  </form>;
}
