// Production requests use verified publications. Forged payloads below only test rejection.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),{startStack}=require('./test-stack.cjs');
const output=process.env.KAUSHALIQ_TEST_OUTPUT||path.resolve(__dirname,'../../docs/phase-5/verification/browser');fs.mkdirSync(output,{recursive:true});
const checks=[],screenshots=[],errors=[];let stack,browser;
function pass(value){checks.push(value);console.log('PASS '+value);}
async function warningLoaded(page){await page.locator('.early-warning-intelligence[data-ready="true"]').waitFor();}
async function scenarioLoaded(page){await page.locator('.scenario-intelligence[data-ready="true"]').waitFor();}
async function warningFilter(page,label,key,value){await page.getByLabel(label,{exact:true}).selectOption(value);await page.waitForFunction(({key,value})=>new URLSearchParams(document.querySelector('.early-warning-intelligence')?.dataset.query??'').get(key)===value,{key,value});await warningLoaded(page);}
async function resetWarnings(page){await page.getByRole('button',{name:'Reset warning filters',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.early-warning-intelligence')?.dataset.query==='limit=25');await warningLoaded(page);}
async function capture(page,file){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,file),fullPage:true,animations:'disabled'});screenshots.push(file);}
async function api(route){const response=await fetch(`http://127.0.0.1:${stack.apiPort}/api/v1/intelligence/${route}`);assert.equal(response.status,200);return response.json();}
async function setEnglish(page){await page.evaluate(()=>{localStorage.setItem('kaushaliq.locale.v1','en-IN');localStorage.setItem('kaushaliq.theme.v1','light');});}
(async()=>{try{
  stack=await startStack(path.resolve(__dirname,'..'),{emailDelivery:false});browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  const published=await api('early-warning?limit=100'),coverage=await api('early-warning/coverage');
  assert.equal(published.data_mode,'verified');assert.ok(published.items.length>0);assert.ok(published.items.every(w=>w.status==='DERIVED'&&['INFO','REVIEW'].includes(w.severity)));
  for(const w of published.items){assert.deepEqual(w.evidence,w.observed_values.map(p=>p.evidence));assert.ok(w.provenance.every(p=>p.observation_ids.every(id=>w.observed_values.some(o=>o.observation_id===id))));}
  const skill=coverage.items.find(r=>r.signal_type==='EMERGING_SKILL_SIGNAL');assert.notEqual(skill.status,'READY');assert.ok(skill.required_data.length);
  await page.goto(stack.base+'/early-warning');await warningLoaded(page);await page.locator('.warning-list').waitFor();assert.ok(await page.locator('.warning-inspect').count());
  assert.match(await page.locator('.early-warning-intelligence').innerText(),/historical/i);assert.equal(await page.locator('.workspace-metric').count(),0);
  pass('Verified historical reviews and coverage facts use exact source observations; unavailable skill types remain not ready');
  await page.locator('.warning-inspect').first().focus();await page.keyboard.press('Enter');await page.locator('.warning-detail').waitFor();assert.match(await page.locator('.warning-detail').innerText(),/Why this signal/i);
  const evidenceButton=page.locator('.warning-detail .real-evidence-link').first();await evidenceButton.click();await page.locator('.evidence-dialog').waitFor();assert.match(await page.locator('.evidence-details').innerText(),/PLFS|Periodic Labour/);assert.match(await page.locator('.evidence-details').innerText(),/[a-f0-9]{64}/);
  await page.keyboard.press('Escape');assert.equal(await evidenceButton.evaluate(e=>e===document.activeElement),true);pass('Keyboard warning inspection, exact evidence/checksum and dialog Escape/focus restoration');
  if(published.total>25){await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.early-warning-intelligence')?.dataset.query.includes('offset=25'));assert.equal(await page.locator('.warning-list tbody tr').count(),published.total-25);await page.getByRole('button',{name:'Previous',exact:true}).click();await warningLoaded(page);}
  await warningFilter(page,'Signal dimension','signal_type','LABOUR_INDICATOR_CHANGE');await warningFilter(page,'Geography','geography_id','in-karnataka');assert.equal(await page.locator('.warning-detail').count(),0);await page.locator('.warning-readiness > .phase5-readiness-list > details > summary').click();assert.match(await page.locator('.warning-readiness').innerText(),/history|period|observation/i);
  await warningFilter(page,'Signal dimension','signal_type','EMERGING_SKILL_SIGNAL');assert.equal(await page.locator('.warning-list').count(),0);assert.match(await page.locator('.warning-readiness').innerText(),/skill|crosswalk|taxonomy/i);
  await resetWarnings(page);await warningFilter(page,'Review level','severity','INFO');assert.equal(await page.locator('.warning-list tbody tr').count(),published.items.filter(w=>w.severity==='INFO').length);
  pass('Bounded pagination, real geography filters, insufficient regional history and explicit unavailable skill readiness');
  await page.goto(stack.base+'/early-warning?signal_type=TRAINING_OUTPUT_ACCELERATION');await warningLoaded(page);assert.equal(await page.locator('.warning-list').count(),0);assert.match(await page.locator('.warning-unavailable').innerText(),/Eligible rules were evaluated/);assert.match(await page.locator('.warning-readiness').innerText(),/Ready/);pass('Eligible training rules below threshold return an honest EMPTY result with readiness preserved');
  await page.goto(stack.base+'/early-warning?series_id=not-connected');await warningLoaded(page);assert.equal(await page.locator('.warning-list').count(),0);await page.getByRole('button',{name:'Reset warning filters',exact:true}).click();await warningLoaded(page);
  await page.goto(stack.base+'/early-warning/?data=sample');await warningLoaded(page);assert.equal(await page.locator('.workspace-metric').count(),0);await page.reload();await warningLoaded(page);pass('Empty filters, reset/refresh and trailing-slash explicit-sample URLs cannot enter legacy intelligence');
  await page.goto(stack.base+'/scenarios');await scenarioLoaded(page);assert.match(await page.locator('.scenario-disclosure').innerText(),/SIMULATION.*NOT OBSERVED DATA/);
  await page.getByRole('button',{name:'Run scenario',exact:true}).click();await page.locator('.scenario-result[data-status="NOT_READY"]').waitFor();assert.match(await page.locator('.scenario-result').innerText(),/impact|relationship|ready/i);assert.equal(await page.locator('.scenario-result [data-simulated-value]').count(),0);
  await capture(page,'skill-shock-not-ready-dark-en-1440.png');pass('Technology adoption preserves explicit assumptions and returns scenario not ready without invented skill effects');
  await page.getByLabel('Scenario method',{exact:true}).selectOption('DIRECT_METRIC_SENSITIVITY');await page.getByLabel('Assumed change (%)',{exact:true}).fill('30');
  const sent=page.waitForRequest(r=>r.url().endsWith('/scenarios/skill-shock')&&r.method()==='POST'),received=page.waitForResponse(r=>r.url().endsWith('/scenarios/skill-shock')&&r.request().method()==='POST');await page.getByRole('button',{name:'Run scenario',exact:true}).click();const payload=(await sent).postDataJSON();
  const sensitivity=await(await received).json();await page.locator('.scenario-result[data-status="SCENARIO"]').waitFor();
  assert.equal(sensitivity.is_simulation,true);assert.ok(Math.abs(sensitivity.results[0].value-sensitivity.baseline.value*1.3)<1e-7);assert.equal(sensitivity.results[0].period,sensitivity.baseline.period);assert.deepEqual(sensitivity.relationships,[]);assert.equal(payload.assumption.kind,'DIRECT_METRIC_CHANGE');
  assert.match(await page.locator('.scenario-result').innerText(),/SIMULATION|simulation|assumption/i);await capture(page,'direct-sensitivity-dark-en-1440.png');
  pass('Direct metric sensitivity uses the unchanged observed baseline, exact user assumption and original period with simulation labels');
  await page.getByLabel('Assumed change (%)',{exact:true}).fill('31');assert.equal(await page.locator('.scenario-result').count(),0);
  await page.getByLabel('Evidence family',{exact:true}).selectOption('labour');await scenarioLoaded(page);await page.getByLabel('Assumed change (%)',{exact:true}).fill('1000');await page.getByRole('button',{name:'Run scenario',exact:true}).click();await page.locator('.scenario-result[data-status="NOT_READY"]').waitFor();assert.match(await page.locator('.scenario-result').innerText(),/domain|range|100/i);
  await page.getByLabel('Assumed change (%)',{exact:true}).fill('1001');assert.equal(await page.getByRole('button',{name:'Run scenario',exact:true}).isDisabled(),true);assert.equal(await page.getByLabel('Assumed change (%)',{exact:true}).getAttribute('aria-invalid'),'true');assert.equal(await page.locator('.scenario-result[data-status="SCENARIO"]').count(),0);
  pass('Changed assumptions invalidate old results; invalid/native-domain assumptions never clip or create fake effects');
  let release;const hold=new Promise(r=>release=r);await page.route('**/api/v1/intelligence/early-warning?**',async r=>{await hold;await r.continue();});await page.goto(stack.base+'/early-warning');await page.locator('.page-content .loading-state .skeleton').first().waitFor();assert.equal(await page.locator('.warning-list').count(),0);await capture(page,'warning-loading-dark-en-1440.png');release();await warningLoaded(page);await page.unroute('**/api/v1/intelligence/early-warning?**');
  await page.route('**/api/v1/intelligence/early-warning?**',r=>r.fulfill({status:503,json:{detail:{code:'EARLY_WARNING_PUBLICATION_UNAVAILABLE'}}}));await page.reload();await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.equal(await page.locator('.warning-list').count(),0);await capture(page,'warning-error-dark-en-1440.png');await page.unroute('**/api/v1/intelligence/early-warning?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await warningLoaded(page);
  pass('Loading Skeleton and API failure/retry never substitute warnings, scenario values or sample intelligence');
  for(const kind of ['forged-change','mixed-version','scenario-as-warning']){const value=structuredClone(published);if(kind==='forged-change')value.items[0].derived_metrics.absolute_change=999;else if(kind==='mixed-version')value.version='wrong-publication';else value.items[0].status='SCENARIO';await page.route('**/api/v1/intelligence/early-warning?**',r=>r.fulfill({json:value}));await page.reload();await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.equal(await page.locator('.warning-list').count(),0);await page.unroute('**/api/v1/intelligence/early-warning?**');}
  await page.goto(stack.base+'/scenarios');await scenarioLoaded(page);await page.getByRole('button',{name:'Run scenario',exact:true}).click();await page.locator('.scenario-result[data-status="NOT_READY"]').waitFor();
  const bad=structuredClone(sensitivity);bad.is_simulation=false;await page.route('**/api/v1/intelligence/scenarios/skill-shock',r=>r.fulfill({json:bad}));await page.getByRole('button',{name:'Run scenario',exact:true}).click();await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.equal(await page.locator('.scenario-result[data-status="SCENARIO"]').count(),0);await page.unroute('**/api/v1/intelligence/scenarios/skill-shock');
  pass('Forged derived values, mixed publications and missing simulation disclosures fail closed');
  await page.route('**/api/v1/intelligence/scenarios/skill-shock',r=>r.fulfill({status:503,json:{detail:{code:'SCENARIO_BASELINE_UNAVAILABLE'}}}));await page.getByRole('button',{name:'Run scenario',exact:true}).click();await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.equal(await page.locator('.scenario-result').count(),0);await page.unroute('**/api/v1/intelligence/scenarios/skill-shock');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.locator('.scenario-result[data-status="NOT_READY"]').waitFor();pass('Scenario provider/evaluation failure is explicit, retry restores readiness and no simulated fallback appears');
  for(const width of [1440,1280,1024,768,390])for(const theme of ['dark','light'])for(const locale of ['en-IN','hi-IN'])for(const route of ['early-warning','scenarios']){
    await page.setViewportSize({width,height:1000});await page.evaluate(({theme,locale})=>{localStorage.setItem('kaushaliq.theme.v1',theme);localStorage.setItem('kaushaliq.locale.v1',locale);},{theme,locale});await page.goto(stack.base+'/'+route);if(route==='early-warning')await warningLoaded(page);else await scenarioLoaded(page);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${route}/${width}/${theme}/${locale}`);assert.equal(await page.locator('html').getAttribute('lang'),locale==='hi-IN'?'hi':'en');await capture(page,`${route}-${theme}-${locale}-${width}.png`);
  }pass('40 verified-context screenshots: both pages, five widths, both themes/languages, no page-wide overflow');
  await page.setViewportSize({width:1440,height:1000});await setEnglish(page);await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.evaluate(()=>localStorage.setItem('kaushaliq.theme.v1','system'));await page.goto(stack.base+'/early-warning');await warningLoaded(page);assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  await page.getByRole('button',{name:'Language: English',exact:true}).click();await page.getByRole('menuitemradio',{name:'हिन्दी',exact:true}).click();assert.equal(await page.locator('html').getAttribute('lang'),'hi');await page.reload();await warningLoaded(page);assert.equal(await page.locator('html').getAttribute('lang'),'hi');await page.getByRole('button',{name:'भाषा: हिन्दी',exact:true}).click();await page.getByRole('menuitemradio',{name:'English',exact:true}).click();assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.equal(await page.locator('.early-warning-intelligence').evaluate(e=>getComputedStyle(e).animationName),'none');pass('Live English-Hindi-English, locale persistence, system appearance and reduced motion');
  await page.setViewportSize({width:390,height:1000});await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('link',{name:'Early warning',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByLabel('Signal dimension',{exact:true}).focus();assert.equal(await page.locator(':focus').evaluate(e=>getComputedStyle(e).outlineStyle!=='none'),true);
  await page.goto(stack.base+'/scenarios/?data=sample');await scenarioLoaded(page);assert.equal(await page.locator('.workspace-metric').count(),0);await page.reload();await scenarioLoaded(page);await page.goto(stack.base+'/skill-gaps');await page.locator('.gap-intelligence').waitFor();await page.goBack();await scenarioLoaded(page);await page.goto(stack.base+'/forecast');await page.locator('.forecast-summary').waitFor();assert.equal(await page.locator('.forecast-model-key').count(),0);pass('Mobile menu/Escape/focus, public refresh/history, real-only scenario boundary and Phase 3/4 gates preserved');
  assert.deepEqual(errors,[]);
}catch(e){errors.push(e.stack);console.error(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,screenshots,errors},null,2));if(browser)await browser.close();if(stack)await stack.stop();}})();
