const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),{startStack}=require('./test-stack.cjs');
const frontend=path.resolve(__dirname,'..'),output=path.resolve(frontend,'../docs/phase-2.9/verification');fs.mkdirSync(output,{recursive:true});
let stack,browser;const checks=[],screenshots=[],errors=[];
function pass(name){checks.push(name);console.log('PASS '+name);}
async function capture(page,file,fullPage=true){await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(output,file),fullPage,animations:'disabled'});screenshots.push(file);}
async function loaded(page){await page.waitForFunction(()=>{const params=new URLSearchParams(location.search),keys=['metric','geography_id','geography_level','reference_period','occupation_code','skill_code','qualification_code','sector_code','source_id','quality_status'];const filters=new URLSearchParams([...params].filter(([k,v])=>keys.includes(k)&&v));if(!params.has('metric'))filters.set('metric','TRAINED');if(!params.has('geography_id'))filters.set('geography_id','in');return document.querySelector('.supply-intelligence')?.dataset.query===filters.toString();});await page.locator('[data-taxonomy-kind]').waitFor();}
(async()=>{try{
stack=await startStack(frontend,{emailDelivery:false});browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const api=`http://127.0.0.1:${stack.apiPort}/api/v1/intelligence`;
const all=await(await fetch(api+'/supply?limit=1000')).json();assert.equal(all.total,323);assert.equal(all.items.filter(r=>r.semantic_category==='TRAINING_OUTPUT').length,287);assert.equal(all.items.filter(r=>r.metric==='TRAINING_CENTRES').length,36);assert.equal(all.capacity.status,'UNAVAILABLE');
await page.goto(stack.base+'/supply');await loaded(page);assert.equal(await page.locator('.workspace-login').count(),1);assert.equal(await page.locator('.supply-observation-table tbody tr').count(),3);assert.match(await page.locator('.supply-quality').innerText(),/120/);assert.equal(await page.locator('.workspace-metric,.data-mode-control').count(),0);
pass('Public supply route consumes323 verified activity/infrastructure records and preserves the quarantined total');
const ev=page.locator('.supply-observation button');await ev.focus();await page.keyboard.press('Enter');await page.locator('.evidence-dialog').waitFor();assert.match(await page.locator('.evidence-details').innerText(),/PMKVY/);assert.match(await page.locator('.evidence-details').innerText(),/Original|original|cell retained/);await capture(page,'activity-evidence-dark-en-1440.png');await page.keyboard.press('Escape');assert.equal(await ev.evaluate(el=>el===document.activeElement),true);pass('Shared evidence exposes source, period, original-cell transformation and hash; Escape restores focus');
await page.getByLabel('Metric',{exact:true}).selectOption('TRAINING_CENTRES');await loaded(page);assert.equal(await page.locator('.supply-observation strong').innerText(),'527');assert.equal(await page.locator('.supply-observation-table tbody tr td').nth(3).innerText(),'527$');
assert.equal(await page.locator('.supply-observation-table thead th').nth(3).innerText(),'Centres');await capture(page,'centres-dark-en-1440.png');await page.locator('.supply-observation button').click();await page.locator('.evidence-dialog').waitFor();assert.match(await page.locator('.evidence-details').innerText(),/Konaseema/);await capture(page,'centres-evidence-dark-en-1440.png');await page.keyboard.press('Escape');
await page.getByLabel('Geography',{exact:true}).selectOption('in-lakshadweep');await loaded(page);assert.equal(await page.locator('.supply-observation strong').innerText(),'1');await page.getByLabel('Metric',{exact:true}).selectOption('TRAINED');await loaded(page);assert.equal(await page.locator('.supply-observation').count(),0);await page.getByText('No verified training observations match these dimensions.',{exact:false}).waitFor();pass('Metric-aware filters keep centres separate, retain527$ and distinguish absent Lakshadweep activity from its observed centre');
await page.goto(stack.base+'/supply?geography_level=district');await loaded(page);assert.equal(await page.locator('.supply-observation-table tbody tr').count(),0);await capture(page,'district-unavailable-dark-en-1440.png');await page.goto(stack.base+'/supply?metric=TRAINED&geography_id=in&reference_period=2024-25');await loaded(page);assert.equal(await page.locator('.supply-observation').count(),0);await page.reload();await loaded(page);assert.equal(await page.getByLabel('Observation period',{exact:true}).inputValue(),'2024-25');await page.goBack();await loaded(page);pass('District, quarantined and incompatible-period queries stay unavailable through refresh/history, never zero');
await page.goto(stack.base+'/supply');await loaded(page);const comp=await(await fetch(api+'/compatibility')).json();assert.equal(comp.status,'INCOMPATIBLE');assert.equal(comp.gap_value,null);assert.equal(comp.checks.length,10);assert.equal(await page.locator('.supply-checks>div').count(),10);assert.match(await page.locator('.supply-readiness').innerText(),/not a shortage|not yet comparable/i);pass('Ten deterministic compatibility dimensions explain stock/flow, unit and mapping blockers without a gap number');
await page.getByLabel('Reference type',{exact:true}).selectOption('industry');await page.locator('[data-taxonomy-kind=industry]').waitFor();assert.equal(await page.locator('.supply-taxonomy tbody tr').count(),25);await page.getByLabel('Search reference code or title',{exact:true}).fill('620');await page.getByRole('button',{name:'Search references',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.supply-taxonomy tbody th')?.textContent==='620');assert.match(await page.locator('.supply-taxonomy tbody').innerText(),/Computer programming/);await page.locator('.supply-taxonomy tbody button').first().click();await page.locator('.evidence-dialog').waitFor();assert.match(await page.locator('.evidence-details').innerText(),/NIC/);await page.keyboard.press('Escape');await page.getByLabel('Reference type',{exact:true}).selectOption('qualification');await page.locator('[data-taxonomy-kind=qualification]').waitFor();assert.match(await page.locator('.supply-taxonomy').innerText(),/No verified references/);pass('Reference explorer reuses partial NIC codes/evidence and keeps unconnected occupation/skill/qualification rows unavailable');
await page.getByLabel('Reference type',{exact:true}).selectOption('industry');await page.locator('[data-taxonomy-kind=industry]').waitFor();await capture(page,'nic-reference-dark-en-1440.png');
await page.getByRole('button',{name:'Language: English',exact:true}).click();await page.getByRole('menuitemradio',{name:'हिन्दी',exact:true}).click();await page.getByRole('heading',{name:'प्रशिक्षण गतिविधि और अवसंरचना',exact:true}).first().waitFor();await page.getByLabel('माप',{exact:true}).waitFor();await page.reload();await loaded(page);assert.equal(await page.locator('html').getAttribute('lang'),'hi');await page.getByRole('button',{name:'भाषा: हिन्दी',exact:true}).click();await page.getByRole('menuitemradio',{name:'English',exact:true}).click();await page.getByLabel('Metric',{exact:true}).waitFor();pass('Immediate English-Hindi-English updates and language persistence apply to training, readiness and reference labels');
for(const width of [1440,1280,1024,768,390])for(const theme of ['dark','light'])for(const locale of ['en-IN','hi-IN']){await page.setViewportSize({width,height:1000});await page.evaluate(({theme,locale})=>{localStorage.setItem('kaushaliq.theme.v1',theme);localStorage.setItem('kaushaliq.locale.v1',locale);},{theme,locale});await page.goto(stack.base+'/supply');await loaded(page);await page.waitForFunction(theme=>document.documentElement.dataset.theme===theme,theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${width}/${theme}/${locale}`);await capture(page,`supply-${theme}-${locale}-${width}.png`);if(width===390&&locale==='hi-IN')await capture(page,`supply-${theme}-${locale}-390-viewport.png`,false);}
pass('20 supply screenshots cover all five widths, both themes and languages with no horizontal page overflow');
await page.evaluate(()=>{localStorage.setItem('kaushaliq.locale.v1','en-IN');localStorage.setItem('kaushaliq.theme.v1','system');});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.goto(stack.base+'/supply');await loaded(page);await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await page.locator('.supply-observation button').focus();assert.equal(await page.locator('.supply-observation button').evaluate(el=>getComputedStyle(el).outlineStyle!=='none'),true);await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('link',{name:'Training supply',exact:true}).waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);pass('System appearance, reduced motion, visible focus and mobile navigation/Escape remain functional');
await page.route('**/api/v1/intelligence/supply*',r=>r.fulfill({status:503,contentType:'application/json',body:'{"detail":{"code":"SUPPLY_PUBLICATION_UNAVAILABLE"}}'}));await page.reload();await page.getByText('Verified training data could not be loaded.',{exact:false}).waitFor();assert.equal(await page.locator('.supply-observation').count(),0);await capture(page,'api-error-light-en-390.png');await page.unroute('**/api/v1/intelligence/supply*');await page.getByRole('button',{name:'Try again',exact:true}).click();await loaded(page);
await page.route('**/api/v1/intelligence/supply/coverage',async r=>{const response=await r.fetch(),value=await response.json();value.version='invalid-version';await r.fulfill({response,json:value});});await page.reload();await page.getByText('Verified training data could not be loaded.',{exact:false}).waitFor();await page.unroute('**/api/v1/intelligence/supply/coverage');pass('API failure and mixed publication versions fail closed with retry, no sample fallback');
await page.goto(stack.base+'/supply?data=sample');await loaded(page);assert.equal(await page.locator('.workspace-metric,.data-mode-control').count(),0);await page.goto(stack.base+'/demand');await page.locator('.demand-native strong').waitFor();assert.equal(await page.locator('.demand-native strong').innerText(),'40,05,028');assert.deepEqual(errors,[]);pass('Supply never exposes simulation; historical NCS value preserved; no uncaught browser errors');
}catch(e){errors.push(e.stack);console.error(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,screenshots,errors},null,2));if(browser)await browser.close();if(stack)await stack.stop();}})();
