const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{chromium}=require('playwright'),{startStack}=require('./test-stack.cjs');
const frontend=path.resolve(__dirname,'..'),output=path.resolve(frontend,'../docs/phase-2.7.1/verification');fs.mkdirSync(output,{recursive:true});
const checks=[],screenshots=[],errors=[];let stack,browser;const pass=s=>{checks.push(s);console.log('PASS '+s);};
async function capture(p,file){await p.screenshot({path:path.join(output,file),fullPage:true,animations:'disabled'});screenshots.push(file);}
function update(sql){execFileSync(process.env.PYTHON||'python',['-c','import sqlite3,sys;d=sqlite3.connect(sys.argv[1]);d.execute(sys.argv[2]);d.commit()',stack.database,sql],{windowsHide:true});}
(async()=>{try{
 stack=await startStack(frontend,{emailDelivery:false,demo:true});browser=await chromium.launch({channel:'msedge',headless:true});const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));
 await p.goto(stack.base+'/auth/signin');await p.getByLabel('Email',{exact:true}).fill(stack.demo.email);await p.getByLabel('Password',{exact:true}).fill(stack.demo.password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForURL(/intelligence/);await p.locator('.real-metric>strong').first().waitFor();assert.deepEqual(await p.locator('.real-metric>strong').allTextContents(),['60.1%','58.2%','3.2%']);const session=(await c.cookies()).find(v=>v.name==='kaushaliq_session');assert.equal(session.httpOnly,true);assert.equal(session.sameSite,'Lax');assert.ok(session.expires*1000-Date.now()>7.99*3600000);pass('Seeded demo uses normal login, eight-hour HttpOnly cookie and unchanged verified observations');
 await p.goto(stack.base+'/auth/verify');await p.waitForURL(/my-intelligence/);await p.goto(stack.base+'/profile');await p.getByLabel('Name',{exact:true}).waitFor();assert.equal(await p.getByLabel('Name',{exact:true}).inputValue(),'KaushalIQ Demo');await p.getByText('FastAPI',{exact:true}).waitFor();await p.goto(stack.base+'/onboarding');await p.getByText('Step 1 of 7',{exact:true}).waitFor();await p.getByRole('button',{name:'Exit and continue later',exact:true}).click();await p.waitForURL(/my-intelligence/);await p.getByRole('link',{name:'Karnataka',exact:true}).waitFor();await p.getByRole('link',{name:'Open analysis',exact:true}).click();await p.waitForURL(/region_id=in/);await p.locator('.real-metric>strong').first().waitFor();assert.deepEqual(await p.locator('.real-metric>strong').allTextContents(),['60.1%','58.2%','3.2%']);pass('Synthetic profile, optional onboarding, canonical watchlist and saved verified query are functional');
 await p.goto(stack.base+'/settings');await p.getByText('Current session',{exact:true}).waitFor();await p.getByText('Google connection is not configured.',{exact:true}).waitFor();await p.getByText('Phone verification is currently unavailable.',{exact:true}).waitFor();pass('Security/settings/session and unavailable provider states are inspectable');
 const matrix=[[1440,'dark','en-IN','/my-intelligence'],[1280,'light','hi-IN','/profile'],[1024,'dark','hi-IN','/settings'],[768,'light','en-IN','/onboarding'],[390,'dark','hi-IN','/my-intelligence'],[390,'light','en-IN','/profile']];
 for(const [width,theme,locale,route]of matrix){await p.setViewportSize({width,height:1000});await p.evaluate(({theme,locale})=>{window.kaushaliqTheme.setPreference(theme);localStorage.setItem('kaushaliq.locale.v1',locale);},{theme,locale});await p.goto(stack.base+route);await p.locator('.personal-page,.onboarding-surface').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`demo-${route.slice(1)}-${theme}-${locale}-${width}.png`);}pass('Six demo screenshots cover all five widths, both themes and languages without overflow');
 await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>localStorage.setItem('kaushaliq.locale.v1','en-IN'));await p.goto(stack.base+'/profile');await p.getByRole('button',{name:'Open account menu'}).click();await p.keyboard.press('Escape');await p.getByRole('button',{name:'Open account menu'}).click();await p.getByRole('button',{name:'Sign out',exact:true}).click();await p.waitForURL(stack.base+'/');await p.goto(stack.base+'/profile');await p.waitForURL(/auth\/signin/);const count=execFileSync(process.env.PYTHON||'python',['-c',"import sqlite3,sys;d=sqlite3.connect(sys.argv[1]);print(d.execute('select count(*) from sessions where revoked_at is not null').fetchone()[0])",stack.database],{encoding:'utf8',windowsHide:true}).trim();assert.equal(count,'1');assert.equal((await p.request.get(`http://127.0.0.1:${stack.apiPort}/__test/otp`)).status(),404);pass('Signout revokes server session; private redirect, Escape/reduced motion and no production test mailbox');await c.close();await stack.stop();
 stack=await startStack(frontend);const v=await browser.newContext({viewport:{width:390,height:844}}),q=await v.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(stack.base+'/auth/signup');for(const [label,value]of [['Name','Verification Test'],['Email','verification-test@example.in'],['Password','VerificationTest9!'],['Confirm password','VerificationTest9!']])await q.getByLabel(label,{exact:true}).fill(value);await q.getByRole('button',{name:'Create account',exact:true}).click();await q.waitForURL(/auth\/verify/);await q.getByText(/v\*\*\*@example.in/).waitFor();
 let code=(await(await q.request.get(`http://127.0.0.1:${stack.apiPort}/__test/otp?target=verification-test@example.in`)).json()).code;
 update("update account_otps set expires_at='2020-01-01T00:00:00+00:00',sent_at='2020-01-01T00:00:00+00:00'");await q.reload();await q.getByLabel('Six-digit verification code').fill(code);await q.getByRole('button',{name:'Verify code',exact:true}).click();await q.getByText('This code has expired. Request a new code when the countdown ends.',{exact:true}).waitFor();await q.getByLabel('Six-digit verification code').fill('');await capture(q,'otp-expired-light-en-390.png');await q.getByRole('button',{name:'Resend code',exact:true}).click();await q.getByRole('button',{name:/Resend available in/}).waitFor();code=(await(await q.request.get(`http://127.0.0.1:${stack.apiPort}/__test/otp?target=verification-test@example.in`)).json()).code;
 for(let i=0;i<5;i++){await q.getByLabel('Six-digit verification code').fill(code==='000000'?'111111':'000000');await q.getByRole('button',{name:'Verify code',exact:true}).click();await q.waitForTimeout(250);}await q.getByText('This code has reached its attempt limit. Request a new code when the countdown ends.',{exact:true}).waitFor();await q.getByLabel('Six-digit verification code').fill('');await capture(q,'otp-attempt-limit-light-en-390.png');pass('OTP expiry, resend/cooldown and attempt exhaustion work; screenshots contain no OTP values');
 // Browser transport fixtures verify honest safe UI states, never a runtime provider fallback.
 await q.route('**/api/auth/verification',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({verification_required:true,state:'TEMPORARILY_UNAVAILABLE',masked_target:'v***@example.in',cooldown_seconds:0,error_code:'email_provider_auth_failed'})}));
 await q.route('**/api/auth/verification/resend',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'email_provider_auth_failed'})}));
 await q.reload();await q.getByText('Email provider credentials were rejected. Contact the local administrator.',{exact:true}).first().waitFor();assert.equal(await q.getByRole('button',{name:'Verify code',exact:true}).isDisabled(),true);await q.getByRole('button',{name:'Resend code',exact:true}).click();await q.getByRole('alert').waitFor();
 await q.evaluate(()=>localStorage.setItem('kaushaliq.locale.v1','hi-IN'));await q.reload();await q.getByText('ईमेल प्रदाता ने क्रेडेंशियल स्वीकार नहीं किए। स्थानीय प्रशासक से संपर्क करें।',{exact:true}).first().waitFor();await capture(q,'otp-provider-error-light-hi-390.png');
 await q.unroute('**/api/auth/verification');await q.route('**/api/auth/verification',r=>r.abort());await q.evaluate(()=>localStorage.setItem('kaushaliq.locale.v1','en-IN'));await q.reload();await q.getByText('The verification service could not be reached. Check your connection and try again.',{exact:true}).first().waitFor();assert.equal(await q.getByRole('button',{name:'Verify code',exact:true}).isDisabled(),true);assert.equal((await(await q.request.get(stack.base+'/api/auth/session')).json()).authenticated,false);await capture(q,'otp-network-error-light-en-390.png');pass('Provider rejection and network failure are honest, reload-safe, bilingual and never grant a session');
 await v.close();assert.deepEqual(errors,[]);
}catch(e){errors.push(String(e));console.error(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,screenshots,errors},null,2));if(browser)await browser.close();if(stack)await stack.stop();}})();
