const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const {chromium}=require('playwright');const {startStack}=require('./test-stack.cjs');
const frontend=path.resolve(__dirname,'..'),output=path.resolve(frontend,'../docs/phase-2.7/verification');fs.mkdirSync(output,{recursive:true});
const checks=[],screenshots=[],errors=[];let stack,browser;
const pass=message=>{checks.push(message);console.log('PASS '+message);};
(async()=>{try{
 stack=await startStack(frontend);browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(stack.base+'/intelligence');await page.locator('.real-metric>strong').first().waitFor();assert.deepEqual(await page.locator('.real-metric>strong').allTextContents(),['60.1%','58.2%','3.2%']);assert.equal(await page.getByRole('link',{name:'Sign in',exact:true}).count(),1);
 await page.goto(stack.base+'/profile');await page.waitForURL(/auth\/signin/);pass('Verified public intelligence is anonymous; private profile remains protected');
 await page.goto(stack.base+'/auth/signup');await page.getByLabel('Name',{exact:true}).fill('Personal Analyst');await page.getByLabel('Email',{exact:true}).fill('personal@example.in');await page.getByLabel('Password',{exact:true}).fill('weak');await page.getByLabel('Confirm password',{exact:true}).fill('weak');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByText('Use 8+ characters with uppercase, lowercase, a number and a special character.',{exact:true}).waitFor();
 await page.getByLabel('Password',{exact:true}).fill('PersonalAccount9!');await page.getByLabel('Confirm password',{exact:true}).fill('PersonalAccount9!');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.waitForURL(/auth\/verify/);await page.getByText('Check p***@example.in for your verification code.').waitFor();assert.equal((await (await page.request.get(stack.base+'/api/auth/session')).json()).authenticated,false);await page.getByRole('button',{name:/Resend available in/}).waitFor();
 const initialCode=(await (await page.request.get(`http://127.0.0.1:${stack.apiPort}/__test/otp?target=personal%40example.in`)).json()).code; await page.getByLabel('Six-digit verification code').fill(initialCode==='000000'?'999999':'000000');await page.getByRole('button',{name:'Verify code',exact:true}).click();await page.getByText(/The code is invalid, expired/).waitFor();await page.screenshot({path:path.join(output,'otp-invalid-desktop.png'),fullPage:true,animations:'disabled'});await page.reload();await page.getByText('Check p***@example.in for your verification code.').waitFor();
 for(const theme of ['light','dark'])for(const locale of ['en-IN','hi-IN'])for(const width of [1440,1280,1024,768,390]){await page.setViewportSize({width,height:1000});await page.evaluate(({theme,locale})=>{window.kaushaliqTheme.setPreference(theme);localStorage.setItem('kaushaliq.locale.v1',locale);},{theme,locale});await page.reload();await page.locator('.verification-surface').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const file='otp-'+theme+'-'+locale+'-'+width+'.png';await page.screenshot({path:path.join(output,file),fullPage:true,animations:'disabled'});screenshots.push(file);}await page.evaluate(()=>{window.kaushaliqTheme.setPreference('dark');localStorage.setItem('kaushaliq.locale.v1','en-IN');});await page.setViewportSize({width:1440,height:1000});await page.reload();
 const delivered=await (await page.request.get(`http://127.0.0.1:${stack.apiPort}/__test/otp?target=personal%40example.in`)).json();await page.getByLabel('Six-digit verification code').fill(delivered.code);await page.getByRole('button',{name:'Verify code',exact:true}).click();await page.waitForURL(/onboarding/);await page.getByText('Step 1 of 7').waitFor();
 pass('Strong signup, actual backend OTP confirmation, masked address, invalid code, countdown and refresh; no session before verification');
 await page.getByLabel('What is your highest qualification?').selectOption('graduate');await page.getByLabel('Degree / qualification (optional)').fill('BSc');await page.getByRole('button',{name:'Save and continue',exact:true}).click();await page.getByText('Step 2 of 7').waitFor();await page.getByLabel('Data & Analytics',{exact:true}).check();await page.getByRole('button',{name:'Save and continue',exact:true}).click();await page.getByText('Step 3 of 7').waitFor();
 await page.getByLabel('Add a skill you know').fill('Python');await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByRole('button',{name:'Save and continue',exact:true}).click();await page.getByText('Step 4 of 7').waitFor();await page.getByLabel('Improve current skills',{exact:true}).check();await page.getByRole('button',{name:'Save and continue',exact:true}).click();await page.getByText('Step 5 of 7').waitFor();await page.getByLabel('Current region (optional)',{exact:true}).selectOption('in-karnataka');await page.getByLabel('Karnataka',{exact:true}).check();await page.getByLabel('Interested in remote opportunities',{exact:true}).check();await page.getByRole('button',{name:'Save and continue',exact:true}).click();await page.getByText('Step 6 of 7').waitFor();await page.getByRole('button',{name:'Skip for now',exact:true}).click();await page.getByRole('button',{name:'Finish onboarding',exact:true}).click();await page.waitForURL(/my-intelligence/);await page.getByText('Python',{exact:true}).waitFor();await page.reload();await page.getByText('Python',{exact:true}).waitFor();pass('Optional seven-step onboarding persists all sections, self-reported origin and resume skip; My Intelligence contains actual user context');
 await page.getByRole('button',{name:'Follow',exact:true}).click();await page.getByRole('button',{name:'Unfollow',exact:true}).waitFor();await page.getByLabel('Analysis title',{exact:true}).fill('National observed rates');await page.getByRole('button',{name:'Save configuration',exact:true}).click();await page.getByRole('link',{name:'Open analysis',exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'Unfollow',exact:true}).waitFor();await page.getByRole('link',{name:'Open analysis',exact:true}).click();await page.locator('.real-metric>strong').first().waitFor();assert.equal(await page.locator('.real-metric>strong').first().innerText(),'60.1%');pass('Canonical watchlist and saved query persist; reopening uses unchanged current verified observations');
 await page.goto(stack.base+'/profile');const name=page.getByLabel('Name',{exact:true});await name.fill('Updated Analyst');await name.locator('xpath=ancestor::form').getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Changes saved.',{exact:true}).waitFor();await page.reload();await page.getByLabel('Name',{exact:true}).waitFor();assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Updated Analyst');
 const fixture=path.join(output,'synthetic-resume.docx');execFileSync(process.env.PYTHON||'python',['-c',"import zipfile,sys; z=zipfile.ZipFile(sys.argv[1],'w'); z.writestr('word/document.xml','<w:document xmlns:w=\"urn:w\"><w:p><w:t>Skills: SQL, Testing</w:t></w:p><w:p><w:t>Education: BSc</w:t></w:p><w:p><w:t>Experience: Analyst</w:t></w:p></w:document>'); z.close()",fixture]);
 await page.locator('input[type=file]').setInputFiles(fixture);await page.getByRole('heading',{name:'Review extracted information'}).waitFor();await page.getByLabel('Skills · SQL',{exact:true}).check();await page.getByLabel('Skills 1',{exact:true}).fill('SQL querying');await page.getByRole('button',{name:'Confirm selected information',exact:true}).click();await page.getByText('SQL querying',{exact:true}).waitFor();assert.equal((await page.request.get(stack.base+'/api/v1/me/resume/download')).status(),200);await page.getByRole('button',{name:'Delete resume and associated derived information',exact:true}).click();await page.getByRole('link',{name:'Download resume',exact:true}).waitFor({state:'hidden'});assert.equal((await page.request.get(stack.base+'/api/v1/me/resume/download')).status(),404);pass('Profile name editing persists; resume candidates require explicit selection/edit/confirmation; authenticated download and real deletion work');
 await page.goto(stack.base+'/settings');await page.getByLabel('Current password',{exact:true}).last().fill('PersonalAccount9!');await page.getByLabel('New password',{exact:true}).fill('ChangedAccount9!');await page.getByLabel('Confirm password',{exact:true}).fill('ChangedAccount9!');await page.getByRole('button',{name:'Change password',exact:true}).click();await page.getByText('Password changed. Other sessions have been signed out.').waitFor();await page.getByText('Google connection is not configured.').waitFor();await page.getByText('GitHub connection is not configured.').waitFor();await page.getByText('Phone verification is currently unavailable.',{exact:true}).waitFor();await page.getByLabel('New verified datasets',{exact:true}).check();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Changes saved.',{exact:true}).waitFor();pass('Password strength/change, sessions, honest provider states and persisted alert preferences without invented events');
 // Validate optional exit independently of a completed profile.
 await page.goto(stack.base+'/onboarding');await page.getByRole('button',{name:'Exit and continue later',exact:true}).click();await page.waitForURL(/my-intelligence/);pass('Onboarding can be exited; public intelligence is never completion-gated');
 for(const theme of ['light','dark'])for(const locale of ['en-IN','hi-IN'])for(const width of [1440,1280,1024,768,390]){
   await page.setViewportSize({width,height:1000});await page.evaluate(({theme,locale})=>{window.kaushaliqTheme.setPreference(theme);localStorage.setItem('kaushaliq.locale.v1',locale);},{theme,locale});
   for(const route of ['/profile','/settings','/my-intelligence','/onboarding']){await page.goto(stack.base+route);await page.locator('.personal-page,.onboarding-surface').waitFor();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,route+' '+width+' '+locale);const file=route.slice(1)+'-'+theme+'-'+locale+'-'+width+'.png';await page.screenshot({path:path.join(output,file),fullPage:true,animations:'disabled'});screenshots.push(file);}
 }
 pass('80 account/onboarding captures: five widths, both themes and English/Hindi; no horizontal overflow');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>localStorage.setItem('kaushaliq.locale.v1','en-IN'));await page.goto(stack.base+'/profile');await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'Open account menu'}).click();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open account menu'}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL(stack.base+'/');await page.goto(stack.base+'/intelligence');await page.locator('.real-metric>strong').first().waitFor();await page.goto(stack.base+'/profile');await page.waitForURL(/auth\/signin/);pass('Keyboard/Escape, reduced motion, actual logout, public access after logout and private route protection');
 await page.getByLabel('Email',{exact:true}).fill('personal@example.in');await page.getByLabel('Password',{exact:true}).fill('ChangedAccount9!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(/profile/);await page.goto(stack.base+'/profile');await page.getByLabel('Name',{exact:true}).waitFor();execFileSync(process.env.PYTHON||'python',['-c',"import sqlite3,sys; d=sqlite3.connect(sys.argv[1]); d.execute(\"update sessions set revoked_at='2026-01-01T00:00:00+00:00' where revoked_at is null\"); d.commit()",stack.database]);const staleName=page.getByLabel('Name',{exact:true});await staleName.fill('Unsaved after revocation');await staleName.locator('xpath=ancestor::form').getByRole('button',{name:'Save changes',exact:true}).click();await page.waitForURL(/auth\/signin\?reason=expired/);await page.getByText('Your session has expired. Please sign in again.',{exact:true}).waitFor();await page.goto(stack.base+'/intelligence');await page.locator('.real-metric>strong').first().waitFor();pass('Revoked sessions clear private UI on the next API request; anonymous public knowledge remains available');
 await context.close();await stack.stop();stack=await startStack(frontend,{emailDelivery:false});const plain=await browser.newContext({viewport:{width:390,height:844}});const unavailable=await plain.newPage();unavailable.on('pageerror',e=>errors.push(e.message));await unavailable.goto(stack.base+'/auth/signup');await unavailable.getByLabel('Name',{exact:true}).fill('Pending Account');await unavailable.getByLabel('Email',{exact:true}).fill('unconfigured@example.in');await unavailable.getByLabel('Password',{exact:true}).fill('PendingAccount9!');await unavailable.getByLabel('Confirm password',{exact:true}).fill('PendingAccount9!');await unavailable.getByRole('button',{name:'Create account',exact:true}).click();await unavailable.waitForURL(/auth\/verify/);await unavailable.screenshot({path:path.join(output,'otp-unconfigured-mobile.png'),fullPage:true,animations:'disabled'});await unavailable.getByText('Email verification is not configured.',{exact:true}).waitFor();assert.equal((await (await unavailable.request.get(stack.base+'/api/auth/session')).json()).authenticated,false);assert.equal((await unavailable.request.get(`http://127.0.0.1:${stack.apiPort}/__test/otp`)).status(),404);await unavailable.screenshot({path:path.join(output,'otp-unconfigured-mobile.png'),fullPage:true,animations:'disabled'});await unavailable.goto(stack.base+'/intelligence');await unavailable.locator('.real-metric>strong').first().waitFor();await plain.close();pass('Normal application with unconfigured delivery never grants a session or exposes a test OTP; anonymous verified data still works');
 assert.deepEqual(errors,[]);
}catch(e){errors.push(String(e));console.error(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,screenshots,errors},null,2));if(browser)await browser.close();if(stack)await stack.stop();}})();
