import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useLocale } from '../hooks/usePreferences';
import { usePersonalProfile } from '../features/account/usePersonalProfile';
import { useIntelligenceData } from '../features/real-intelligence/dataContext';
import { accountRequest } from '../features/account/api';
import type { SavedAnalysis, WatchItem } from '../features/account/contracts';
import { preferenceLabel } from '../features/account/config';
import { Button } from '../components/ui/Buttons';

export function MyIntelligencePage(){
 const {t}=useLocale();const {profile,error,csrf}=usePersonalProfile();const {catalog}=useIntelligenceData();const [items,setItems]=useState<WatchItem[]>([]);const [reports,setReports]=useState<SavedAnalysis[]>([]);const [kind,setKind]=useState<'regions'|'industries'>('regions');const [entity,setEntity]=useState('in');const [search,setSearch]=useState('');const [busy,setBusy]=useState(false);const [failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;Promise.all([accountRequest<{items:WatchItem[]}>('/v1/me/watchlist',csrf),accountRequest<{items:SavedAnalysis[]}>('/v1/me/reports',csrf)]).then(([w,r])=>{if(active){setItems(w.items);setReports(r.items);}}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[csrf]);
 async function action(path:string,method:string,body?:unknown){setBusy(true);setFailed(false);try{await accountRequest('/v1/me/'+path,csrf,method,body);const [w,r]=await Promise.all([accountRequest<{items:WatchItem[]}>('/v1/me/watchlist',csrf),accountRequest<{items:SavedAnalysis[]}>('/v1/me/reports',csrf)]);setItems(w.items);setReports(r.items);}catch{setFailed(true);}finally{setBusy(false);}}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);void action('reports','POST',{title:form.get('title'),route:'/intelligence',query:{region_id:form.get('region'),period:form.get('period')}});}
 if(error)return <p role="alert">{t('personal.error')}</p>;if(!profile)return <p role="status">{t('personal.loading')}</p>;
 const choices=kind==='regions'?catalog?.regions.map(r=>({id:r.region_id,name:r.name})):catalog?.industries.map(i=>({id:i.industry_id,name:`${i.nic_code} · ${i.name}`}));
 return <div className="personal-page"><div className="personal-context"><strong>{profile.user.name}</strong><p>{t('personal.intro')}</p><div className="personal-actions"><Link to="/profile">{t('account.profile')}</Link><Link to="/onboarding">{t('personal.onboard')}</Link><Link to="/intelligence">{t('personal.public')}</Link></div></div><section className="personal-section"><h2>{t('personal.profile')}</h2><dl>{(['interests','skills','career','geography'] as const).map(section=><div key={section}><dt>{t(`personal.${section}`)}</dt><dd>{section==='interests'?profile.sections.interests.map(id=>preferenceLabel(t,"i",id)).join(' · '):section==='skills'?profile.sections.skills.map(s=>s.name).join(' · '):section==='career'?profile.sections.career.goals.map(id=>preferenceLabel(t,"g",id)).join(' · '):profile.sections.geography.preferred.map(id=>catalog?.regions.find(r=>r.region_id===id)?.name||id).join(' · ')}</dd></div>)}</dl><p>{t('personal.empty')}</p></section>
  <section className="personal-section"><h2>{t('personal.watchlist')}</h2><p>{t('personal.watchEmpty')}</p><div className="personal-inline"><label>{t('personal.kind')}<select aria-label={t("personal.kind")} value={kind} onChange={e=>{const next=e.target.value as typeof kind;setKind(next);setEntity(next==='regions'?'in':catalog?.industries[0]?.industry_id||'');}}><option value="regions">{t('common.regions')}</option><option value="industries">{t('common.industries')}</option></select></label><label>{t('personal.search')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="personal-inline"><label>{t('personal.entity')}<select aria-label={t("personal.entity")} value={entity} onChange={e=>setEntity(e.target.value)}>{choices?.filter(v=>v.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())||v.id===entity).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><Button pending={busy} disabled={!entity||!catalog} onClick={()=>void action('watchlist','POST',{kind,entity_id:entity})}>{t('personal.follow')}</Button></div><ul className="session-list">{items.map(item=><li key={item.id}><Link to={(item.kind==='regions'?'/regions?region_id=':'/industries?industry=')+encodeURIComponent(item.entity_id)}>{item.name}</Link><Button variant="quiet" pending={busy} onClick={()=>void action('watchlist/'+item.id,'DELETE')}>{t('personal.unfollow')}</Button></li>)}</ul></section>
  <section className="personal-section"><h2>{t('personal.analyses')}</h2><p>{t('personal.analysisNote')}</p><form onSubmit={save} className="personal-inline"><label>{t('personal.analysisTitle')}<input name="title" required maxLength={120}/></label><label>{t('personal.currentRegion')}<select aria-label={t("personal.currentRegion")} name="region">{catalog?.regions.map(r=><option value={r.region_id} key={r.region_id}>{r.name}</option>)}</select></label><label>{t('personal.period')}<select aria-label={t("personal.period")} name="period">{['2023-24','2022-23','2021-22','2020-21','2019-20','2018-19','2017-18'].map(period=><option key={period}>{period}</option>)}</select></label><Button type="submit" pending={busy} disabled={!catalog}>{t('personal.saveAnalysis')}</Button></form><ul className="session-list">{reports.map(report=><li key={report.id}><div><strong>{report.title}</strong>{report.updated_data&&<small>{t('personal.updated')}</small>}<Link to={report.route+'?'+new URLSearchParams(report.query).toString()}>{t('personal.open')}</Link></div><Button variant="quiet" pending={busy} onClick={()=>void action('reports/'+report.id,'DELETE')}>{t('personal.delete')}</Button></li>)}</ul></section>{failed&&<p role="alert">{t('personal.error')}</p>}
 </div>;
}
