import {useLocale} from '../../hooks/usePreferences';
import {StatusBadge} from '../../components/ui/StatusBadge';
import type {Evidence,Source} from '../real-intelligence/contracts';
import {contextLabel,metricLabel,reasonLabel,unitLabel} from '../phase5/labels';
import type {Warning} from './contracts';
export type EvidenceSelection={evidence:Evidence;source?:Source;period:string};
export function WarningDetail({warning,sources,onEvidence}:{warning:Warning;sources:Source[];onEvidence:(value:EvidenceSelection)=>void}){
  const {t,locale}=useLocale(),nf=new Intl.NumberFormat(locale,{maximumFractionDigits:2}),delta=new Intl.NumberFormat(locale,{maximumFractionDigits:2,signDisplay:'exceptZero'}),d=warning.derived_metrics;
  const changeUnit=d.change_unit==='percentage points'?t('phase5.pp'):unitLabel(t,d.change_unit??'');
  return <section className="warning-detail phase5-detail" aria-labelledby="warning-detail-heading" data-signal-id={warning.signal_id}>
    <header><p className="section-kicker">{t('warning.why')}</p><h2 id="warning-detail-heading">{metricLabel(t,warning.observed_values.at(-1)?.identity.metric??warning.entity_name)}</h2><p><span lang="en">{warning.geography.geography_name}</span> · {warning.period}</p><p>{t('warning.context')}: {contextLabel(t,warning.observed_values.at(-1)?.identity??{})}</p><StatusBadge kind="derived"/></header>
    <dl className="phase5-facts"><div><dt>{t('real.period')}</dt><dd>{warning.period}</dd></div><div><dt>{t('warning.compared')}</dt><dd>{warning.comparison_period??'—'}</dd></div><div><dt>{t('warning.severity')}</dt><dd>{t(`warning.${warning.severity}`)}</dd></div></dl>
    {d.absolute_change!==null&&<section className="warning-comparison"><h3>{t('warning.metrics')}</h3><dl className="phase5-facts"><div><dt>{t('warning.change')}</dt><dd>{delta.format(d.absolute_change)} <small>{changeUnit}</small></dd></div>{d.growth_percent!==null&&<div><dt>{t('warning.growth')}</dt><dd>{delta.format(d.growth_percent)}%</dd></div>}{d.previous_growth_percent!==null&&<div><dt>{t('warning.previousGrowth')}</dt><dd>{delta.format(d.previous_growth_percent)}%</dd></div>}{d.acceleration_pp!==null&&<div><dt>{t('warning.acceleration')}</dt><dd>{delta.format(d.acceleration_pp)} <small>{t('phase5.pp')}</small></dd></div>}</dl></section>}
    <section className="warning-trigger"><h3>{t('warning.rule')}</h3><p>{warning.trigger_rule.threshold!==null&&<strong>≥ {nf.format(warning.trigger_rule.threshold)} {warning.trigger_rule.threshold_unit==='percentage points'?t('phase5.pp'):warning.trigger_rule.threshold_unit}</strong>}</p><p>{warning.signal_type==='DATA_COVERAGE_WARNING'?reasonLabel(t,warning.trigger_rule.rule_id):t(warning.signal_type==='LABOUR_INDICATOR_CHANGE'?'warning.labourRule':'warning.trainingRule')}</p><code lang="en">{warning.trigger_rule.rule_id} · {warning.trigger_rule.version}</code></section>
    <section><h3>{t('warning.observations')}</h3><div className="real-table-wrap" tabIndex={0} role="region" aria-label={t('warning.observations')}><table><caption>{t('warning.observations')}</caption><thead><tr><th>{t('real.period')}</th><th>{t('forecast.observed')}</th><th>{t('real.source')}</th><th>{t('phase5.evidence')}</th></tr></thead><tbody>{warning.observed_values.map(p=><tr key={p.observation_id}><th scope="row">{p.period}{p.partial&&<small>{t('forecast.partial')}</small>}</th><td>{nf.format(p.value)} {unitLabel(t,p.unit)}<small><StatusBadge kind="observed"/></small></td><td lang="en">{sources.find(s=>s.source_id===p.source_id)?.publisher}</td><td><button type="button" className="real-evidence-link" onClick={()=>onEvidence({evidence:p.evidence,source:sources.find(s=>s.source_id===p.source_id),period:p.period})} aria-label={`${t('phase5.evidence')} ${p.period}`}>{t('phase5.evidence')}</button></td></tr>)}</tbody></table></div></section>
    <section><h3>{t('warning.qualification')}</h3><p>{t(warning.signal_type==='DATA_COVERAGE_WARNING'?'warning.coverageNote':'warning.historical')}</p><p>{t('warning.qualificationNote')}</p><h3>{t('phase5.limitations')}</h3><p>{t('warning.limitNote')}</p></section>
    <details className="phase5-method"><summary>{t('phase5.technical')} · {warning.limitations.length}</summary><p lang="en">{warning.trigger_rule.methodology}</p><p lang="en">{warning.confidence_or_qualification}</p><ul lang="en">{warning.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul><p>{t('phase5.sourceNative')}</p></details>
  </section>;
}
